### ISSUE TITLE
how to correlate logs with traces?

### ISSUE THREAD

**Issue by breathe** [DataDog/heroku-buildpack-datadog#197]
I'm using heroku-buildpack-datadog to integrate datadog into a ruby-on-rails application running on heroku.

I've installed the dd_tracer agent and configured the heroku logdrain -- metrics, traces and logs are all making it to datadog -- however the logs are not correlating against the traces ...

i've tried configuring my application's rails logger like so:

```
  Rails.application.configure do
    config.log_tags = [proc { Datadog.tracer.active_correlation.to_s }]
  end
```

which results in log output like this (as rendered by `heroku logs tail`):

```
2020-07-22T10:44:29.219625+00:00 app[web.1]: [dd.env=production dd.service=checkate-pos-production dd.trace_id=2025735287018585527 dd.span_id=1683259238264168847] Started GET "/v1/locations/4053/queue?token=c74f8f8ef9baeb42692e16e54aa02261" for 69.137.150.205 at 2020-07-22 10:44:29 +0000
```

Messages similar to above renders like so in datadog:

![image](https://user-images.githubusercontent.com/434034/88168225-5c969100-cbd7-11ea-8f36-8b99c47d978e.png)

however the trace_id is not being parsed on datadog side ...

Is there a way to get this to work?  

Is heroku logdrain the intended way to ship logs with trace_id from heroku to datadog or is there another more preferred way to do it?

**Comment by arapulido** [comment]
The log drain is not managed in this project, but I will pass your question to the logs team

**Comment by arapulido** [comment]
Right now, the Heroku logs parser don't currently parse dd.trace_id, I am following up with the team in charge of the Heroku log drain to see what we should do.

In the mean time I would recommend you to try to do either of these two options:

* Parse the heroku log drain yourself, and add a tracer remapper as explained here: https://docs.datadoghq.com/tracing/faq/why-cant-i-see-my-correlated-logs-in-the-trace-id-panel/?tab=custom

* Instead of the log drain, use the normal log Datadog agent (by setting `DD_LOGS_ENABLED=true`) for your Ruby logging, so it uses the Ruby integration, and follow the instructions here: https://docs.datadoghq.com/tracing/connect_logs_and_traces/ruby/

Let me know if that works for you

**Comment by robatshogun** [comment]
@arapulido Hi there. Thanks for the information you posted here. Has this issue since been resolved or are there any pertinent updates? We are currently trying to work through this issue at the moment.

Thanks!

cc: @dalizard

**Comment by arapulido** [comment]
@robatshogun What exactly are you trying to achieve? Can you share a bit more about your environment, please?

**Comment by robatshogun** [comment]
Hi @arapulido, thanks for your response. We actually have figured out our issue(s).
