### ISSUE TITLE
Dyno metrics don't show

### ISSUE THREAD

**Issue by Whitespace** [DataDog/heroku-buildpack-datadog#2]
I'm running this in prod, and although trace metrics show up, dyno metrics don't show up in the infrastructure tab.

The hosts are visible, but there's no data.

Ideally I'd be able to disable the infrastructure metrics and only keep the Trace metrics, but I'm not sure if that's possible.

**Comment by jyee** [comment]
There really aren't any infrastructure metrics gathered by the buildpack (nor were there by the original project this was forked from), so that's why there's no data. I'm not quite sure how trace metrics vs. infrastructure metrics will be handled once tracing moves out of beta, but we'll get a better idea of how to handle enabling/disabling closer to that time.

To get Dyno metrics, you'll need to setup a Log Drain, such as the [heroku-datadog-drain](https://github.com/ozinc/heroku-datadog-drain) or [heroku-datadog-drain-go](https://github.com/apiaryio/heroku-datadog-drain-golang)(this is the drain I've been using)
