### ISSUE TITLE
ERROR | Cannot write json file: /opt/datadog-agent/run/version-history.json with Agent 7.22

### ISSUE THREAD

**Issue by pcreux** [DataDog/heroku-buildpack-datadog#205]
Hello there,

We've just upgraded to the latest buildpack ([v1.19](https://github.com/DataDog/heroku-buildpack-datadog/releases/tag/1.19)) which upgrades the Agent from `7.20` to `7.22`.

Agent `7.22` introduces an Agent History File (see https://github.com/DataDog/datadog-agent/pull/5922) which is attempting to write a file to `/opt/datadog-agent/run/version-history.json` and logs an error as `/opt/*` is not writable on Heroku.

It'd be nice to prevent such an error from being logged.

**Comment by breathe** [comment]
I am also getting this error since the update.

As well as a whole bunch of log spam from my sql server do to a huge number of sql requests that are only valid on aws postgres -- which appeared in our logs _right around_ the time of the datadog buildpack updates.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/434034/91630795-acfccd80-e991-11ea-8edc-7e1607c3cdc5.png">

**Comment by carltondickson** [comment]
Getting this too...am using PHP and connecting to the dyno to perform `php artisan tinker`.
My commands still work but would be nice to not have this error.

**Comment by arapulido** [comment]
Thanks for reporting this! This shouldn't happen. I will investigate

**Comment by arapulido** [comment]
@breathe For the postgres issue, this will be fixed in the next version of the agent: https://github.com/DataDog/integrations-core/issues/7450

**Comment by arapulido** [comment]
This is now fixed in the buildpack 1.20 release. Thanks again for reporting!
