### ISSUE TITLE
Complaining of unset ENV variables

### ISSUE THREAD

**Issue by justinkchen** [DataDog/heroku-buildpack-datadog#25]
I have the DD_API_KEY and DD_HOSTNAME set as config vars in my heroku setup.  They show up properly in heroku config.  But when I load up a console with `heroku ps:exec` it complains about those variables not being set.

**Comment by jyee** [comment]
@justinkchen This is because running `heroku ps:exec` does not load config vars into `env` (see Heroku's documentation at https://devcenter.heroku.com/articles/exec#environment-variables).

Depending on your needs, maybe `heroku run bash` would be better, since it spins up a new dyno and loads the config vars into `env`?

**Comment by justinkchen** [comment]
Thanks for that info @jyee!
