### ISSUE TITLE
Postgres integration's "cardinality"

### ISSUE THREAD

**Issue by ikonst** [DataDog/heroku-buildpack-datadog#366]
When integrating with Postgres, is the assumption that each dyno in the fleet will be instrumenting the same Postgres host, i.e. the Postgres host will have N connections from N agents, each querying for the same stats and sending the same stats to Datadog?

**Comment by arapulido** [comment]
Because of the way Heroku works (with all dynos for the same app having the same configuration), if you don't use the prerun script to disable the integration, it will run on all dynos, which is not needed. 
You can add a prerun script (https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script) that disables the integration for specific dynos.

Feel free to reopen with more details if the tip above doesn't doesn't work for you.

**Comment by ikonst** [comment]
So, ostensibly, if your DD agent monitors Postgres, then you should pick a single dyno that'll monitor the DB (e.g. "web.1") and do `DD_ENABLE_DBM=false` on all others?
