### ISSUE TITLE
Turn on OTLP ingestion

### ISSUE THREAD

**Issue by aenand** [DataDog/heroku-buildpack-datadog#367]
Hello! Is there a way to turn on OTLP ingestion for a datadog agent running on a Heroku dyno? I see this [doc](https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=host) on how to add OTLP for Datadog and it mentions a `datadog.yaml` file but I don't see any mention of this file in the heroku-buildpack-datadog documentation. Thanks!

**Comment by arapulido** [comment]
Hello @aenand ! I haven't tried this yet, but using the Docker instructions (i.e. setting up the right env variables, instead of the configuration file) should work: https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=docker

Can you try that and report back if it works? Thanks!

**Comment by arapulido** [comment]
Closing this issue as we never heard back. Please, reopen if this is still an issue
