### ISSUE TITLE
Agent reports host system metrics, not dyno metrics

### ISSUE THREAD

**Issue by sdalezman** [DataDog/heroku-buildpack-datadog#39]
Hi Datadog,

Not sure if this is fixed at the buildpack level or the app level. But from within DataDog the infrastructure list data is displaying data for the underlying machines dynos are hosted on. This is pretty valueless from my perspective. I'm concerned about the memory usage of dyno's themselves not data about the underlying machines. 

This is particularly problematic because if you're using DataDog for APM tracing, you're forced to pay for the infrastructure host as well. It's pretty hard for me to justify that I should be paying for incorrect data and thus increasing the cost of the apm tools by 33%. 

Would be great to see the actual dyno level information, because that is the actionable data that I can work from. From an infrastructure perspective, the native Heroku stats tools provide a truer view (minus being able to capture one-off + scheduled dynos) than the DataDog tool. Is there a timeline on when this will be fixed?

**Comment by undergroundwebdesigns** [comment]
@sdalezman FYI, there are a couple log-drain apps that will allow you to get the Heroku dyno into Datadog (e.g. CPU, memory usage, etc.) such as [this one](https://github.com/apiaryio/heroku-datadog-drain-golang). It still doesn't show up on the infrastructure page but at least you have access to the data in order to monitor it and include it in dashboards.

I'd love to see a better solution that allows this data to be reported by the buildpack / DD agent directly so that it "just works" without the extra setup.

**Comment by jyee** [comment]
Unfortunately, getting actual dyno metrics from within a Heroku dyno is not easy—and for some metrics is impossible). This is due to a combination of limitations that Heroku has in its implementation of cgroup containers and in Linux itself.

The reason you can get per-dyno metrics in both log-drains and Heroku's native tools is because those are gathered on the host machine level, rather than from inside the dyno (container).

For a good read on the topic (in particular, memory metrics), see https://fabiokung.com/2014/03/13/memory-inside-linux-containers/

In terms of pricing, you should be paying the same. The Datadog APM is bundled as part of the Datadog Agent v6 and relies on it to send traces to Datadog. If you have questions about billing, you should contact your Customer Success Manager or sales@datadoghq.com

**Comment by undergroundwebdesigns** [comment]
@jyee I'm aware of those limitations, and that it's not an easy problem to solve. 

None the less, some ability to capture the dyno metrics (likely a log-drain) and then have them correspond back to individual "hosts" within datadog and over-write the data the agent is natively gathering on CPU usage, ram usage, etc would be extremely valuable. As I said above, we're currently using a logdrain to pull this dyno runtime data into Datadog for graphing and alerts, but because that data is not tied to the individual hosts there are some major limitations. A glaring example is that the entire "host maps" page is virtually useless to us. More subtle is that clicking for details of an APM trace doesn't show accurate ram usage or CPU usage at the time the trace was collected, making it more difficult than it should be to determine if a slow request was due to the dyno swapping, or running over max CPU.

Regarding price, I know that APM requires the basic server reporting, and so we're not really paying "more" for APM, but we are paying the same amount and getting _less_ than those on other platforms, so I do understand @sdalezman 's frustrations there.

While not a dealbreaker for us, I (and I'm sure others using Datadog on Heroku) would be very happy to see some sort of solution to this.

**Comment by msiebuhr** [comment]
Also, is there a way to turn the machine-level metrics off? They really are quite pointless to us - and quite confusing, as they don't really correlate with how *our* code runs on Heroku...

**Comment by jyee** [comment]
I'm going to close this out. There is now an env var `DD_DISABLE_HOST_METRICS` that will disable host metrics collection.
