### ISSUE TITLE
An option to turn off `dyno:XX` tags

### ISSUE THREAD

**Issue by msiebuhr** [DataDog/heroku-buildpack-datadog#60]
We have an app to parse and gather metrics on Heroku requests, which is itself deployed to Heroku.

In particular, we set a `dyno`-tag on everything going through, so we can split eg. load and request information per dyno. BUT the buildpack also forcibly adds dyno-info from the drain itself.

So we end up with metrics that have two dynos, eg `heroku_router_service_seconds:1|h|#dyno:web.1,dyno:web.7`.

This greatly confuses the datadog dashboards we have running...

**Comment by msiebuhr** [comment]
For now, I have forked this repository and applied the following patch. Everything now shows up as expected in DataDog.

```patch
diff --git a/extra/datadog.sh b/extra/datadog.sh
index a90a183..fd76b8c 100644
--- a/extra/datadog.sh
+++ b/extra/datadog.sh
@@ -40,7 +40,7 @@ done
 # Add tags to the config file
 DYNOHOST="$( hostname )"
 DYNOTYPE=${DYNO%%.*}
-TAGS="tags:\n  - dyno:$DYNO\n  - dynotype:$DYNOTYPE"
+TAGS="tags:\n  - dynotype:$DYNOTYPE"

 if [ -n "$HEROKU_APP_NAME" ]; then
   TAGS="$TAGS\n  - appname:$HEROKU_APP_NAME"
```

**Comment by jyee** [comment]
The new prerun.sh feature is a good way to remove or add tags. See the [README](https://github.com/DataDog/heroku-buildpack-datadog#prerun-script) for examples.

**Comment by missmaggiemo** [comment]
Hi @jyee ! I'm still running into the same issue with my Datadog metric collection app-- using a fork of https://github.com/ozinc/heroku-datadog-drain-- even through I have a prerun.sh script that comments out the tag lines.
```
#!/usr/bin/env bash

# Disable the Datadog Agent for datadog drain run machines
if [ "$DYNOTYPE" == "run" ]; then
  DISABLE_DATADOG_AGENT="true"
fi

# Comment out Datadog agent default host tags-- we have our own
sed -i 's/- dyno:/# - dyno:/' "$DATADOG_CONF"
sed -i 's/- dynotype:/# - dynotype:/' "$DATADOG_CONF"
```

I noticed something interesting, though. On the boxes where my Datadog metric collection server is running, the dyno and dynotype tag lines are empty (copied from the machine, so the lines are commented out because the prerun script ran)
```
# Set the host's tags (optional)
# tags:
#   - mytag
#   - env:prod
#   - role:database
tags:
  # - dyno:
  # - dynotype:
```

Screenshot to clarify what I mean by duplicate tags
<img width="1131" alt="screen shot 2019-02-07 at 3 23 14 pm" src="https://user-images.githubusercontent.com/4501235/52442253-ad542000-2af0-11e9-8238-63fa047ccecb.png">

Additionally, in order to test a theory that the agent was started with a different config (or rather a different version of the same file), I tried stopping and starting the agent using the line here https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L135 and saw that the agent did start but metrics weren't making it to Datadog.

Puzzling, right? Advice appreciated!
